root = "."
tmp_dir = "tmp"

[build]
args_bin = ["--port", "4321"]
bin = "./tmp/main"
cmd = "go build -o ./tmp/main ."
delay = 1000
exclude_dir = ["tmp"]
exclude_file = []
exclude_regex = ["_test.go", "_templ.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = [".", "public"]
include_ext = ["go", "html", "css", "js"]
include_file = ["main.go"]
kill_delay = "1s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = true

[proxy]
app_port = 8080
enabled = false
proxy_port = 4321

[screen]
clear_on_rebuild = false
keep_scroll = true
